---
title: "flexdashboard"
author: "Xintao Ding"
date: "10/31/2019"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r import data}
data("rest_inspec")
set.seed(1)
res_data <- rest_inspec %>% 
  sample_n(5000) %>% 
  janitor::clean_names() %>%   # cuisin_description, street
  drop_na() 
#res_data 
```


Column {data-width=650}
-----------------------------------------------------------------------

### Scatterplot 
### looking at coffee shops' score across inspection data in all five boroughs
```{r}

res_data %>% 
  filter(cuisine_description == "Café/Coffee/Tea") %>% 
  mutate(text_label = str_c("Borough: ", boro, "\nGrade: ", grade)) %>% 
  plot_ly(x = ~inspection_date, y = ~score, type = "scatter", mode = "markers", color = ~grade, text = ~text_label, alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Boxplot 
### boros and with their respective "critical" critical flag

```{r}
res_data %>%
  filter(critical_flag == "Critical") %>% 
  mutate(boro = fct_reorder(boro, score)) %>% 
  plot_ly(y = ~score, color = ~boro, type = "box", colors = "Set2")
  
```

### Bartchart
### Number of restaurants inspected in each boro

```{r}
res_data %>% 
  count(boro) %>% 
  mutate(boro = fct_reorder(boro, n)) %>% 
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar")
```

